server:
  port: 9999

spring:
  application:
    name: rocketmqdemo
  # 数据库相关的连接
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/testbasedata?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    driver-class-name: com.mysql.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      password: root
      username: root
      minimum-idle: 5
      maximum-pool-size: 15
      auto-commit: true
      idle-timeout: 30000
      pool-name: DateHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1


rocketmq:
  # \u751F\u4EA7\u8005\u914D\u7F6E
  producer:
    groupName: "test"
    nameServerAddr: localhost:9876
    default: false
    topic: "demo"

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  config-location: classpath:mybatis/mybatis-config.xml


